### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe when trying example.py

### ISSUE THREAD

**Issue by ivan-vasilev** [akapur/pyiqfeed#14]
When I try running the example.py file with parameters -l and/or -n, I get the following exception:

Traceback (most recent call last):
  File "/home/hok/git_local/pyiqfeed/example.py", line 401, in <module>
    get_level_1_quotes_and_trades(ticker="SPY", seconds=30)
  File "/home/hok/git_local/pyiqfeed/example.py", line 32, in get_level_1_quotes_and_trades
    quote_conn = iq.QuoteConn(name="pyiqfeed-Example-lvl1")
  File "/home/hok/git_local/pyiqfeed/pyiqfeed/conn.py", line 728, in __init__
    self._request_fundamental_fieldnames()
  File "/home/hok/git_local/pyiqfeed/pyiqfeed/conn.py", line 1077, in _request_fundamental_fieldnames
    self._send_cmd("S,REQUEST FUNDAMENTAL FIELDNAMES\r\n")
  File "/home/hok/git_local/pyiqfeed/pyiqfeed/conn.py", line 186, in _send_cmd
    self._sock.sendall(cmd.encode(encoding='utf-8', errors='strict'))
BrokenPipeError: [Errno 32] Broken pipe

I have configured the dtn_product_id, dtn_login and dtn_password, and I can see the IQFeed client initializing and making connection to the server, but I still get this exception. My environment is Ubuntu and I can connect to IQFeed with their own client.

**Comment by akapur** [comment]
Sorry. Hadn't committed changes to example.py after a recent refactoring of code. Done now. Pull from the repository.

Also if you are running headless, make sure that as described in the comments in example.py, you modify example.py so the line

svc.launch()
is replaced by
svc.launch(headless=True)

Thanks for reporting the issue.

**Comment by ivan-vasilev** [comment]
Thanks for the fast response, example.py works now.
