### ISSUE TITLE
IQF Client version error: 5.2 not available for download anymore; 6.0 is latest

### ISSUE THREAD

**Issue by antti31** [akapur/pyiqfeed#33]
get_level_1_quotes_and_trades(ticker="SPY", seconds=30)
Level 1 Listener: Authorization Key Received: 99999
Level 1 Listener: Feed Connected
Level 1 Listener: IP Addresses Used: a.b.c.d 60004
Level 1 Listener: Customer Information:
CustomerInfoMsg(svc_type=True, ip_address='a.b.c.d', port=60002, version='6.0.0.5', rt_exchanges=[''''], max_symbols=500, flags='QT_API')
Exception in thread pyiqfeed-Example-lvl1-reader:
Traceback (most recent call last):
  File "C:\Users\abc\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\abc\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\abc\Documents\Python\pyiqfeed\pyiqfeed-master\pyiqfeed\conn.py", line 200, in __call__
    self._process_messages()
  File "C:\Users\abc\Documents\Python\pyiqfeed\pyiqfeed-master\pyiqfeed\conn.py", line 247, in _process_messages
    handle_func(fields)
  File "C:\Users\abc\Documents\Python\pyiqfeed\pyiqfeed-master\pyiqfeed\conn.py", line 279, in _process_system_message
    processing_func(fields)
  File "C:\Users\abc\Documents\Python\pyiqfeed\pyiqfeed-master\pyiqfeed\conn.py", line 321, in _process_current_protocol
    raise UnexpectedProtocol(err_msg)
pyiqfeed.exceptions.UnexpectedProtocol: Desired Protocol 5.2, Server Says Protocol 6.0 in pyiqfeed-Example-lvl1

**Comment by bryaan** [comment]
Iqfeed didn't leave too many older versions available to download.  Try asking them.
