### ISSUE TITLE
OverflowError exception raised in conn.py _process_fundamentals when reading the NAICS field

### ISSUE THREAD

**Issue by vladisld** [akapur/pyiqfeed#73]
Version: 

```
$ pip show pyiqfeed
Name: pyiqfeed
Version: 0.9
Summary: Handles connections to IQFeed, the market data feed by DTN
Home-page: https://github.com/akapur/pyiqfeed
Author: Ashwin Kapur
Author-email: ashwin.kapur@gmail.com
License: GPL v2
Location: /home/vlad/work/.venv/dev/lib/python3.12/site-packages
Requires: numpy
Required-by: 
```

Problem: 

getting the following exception during the 'fundamental_data' QuoteConn listener: 

```
Exception in thread fundamental_data-reader:
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vlad/work/.venv/dev/lib/python3.12/site-packages/pyiqfeed/conn.py", line 211, in __call__
    self._process_messages()
  File "/home/vlad/work/.venv/dev/lib/python3.12/site-packages/pyiqfeed/conn.py", line 256, in _process_messages
    handle_func(fields)
  File "/home/vlad/work/.venv/dev/lib/python3.12/site-packages/pyiqfeed/conn.py", line 1080, in _process_fundamentals
    msg["NAICS"] = fr.read_uint8(fields[self.fundamental_fields.index("NAICS") + 1])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vlad/work/.venv/dev/lib/python3.12/site-packages/pyiqfeed/field_readers.py", line 79, in read_uint8
    return np.uint8(field) if field != "" else 0
           ^^^^^^^^^^^^^^^
OverflowError: Python integer 336390 out of bounds for uint8
```

It seems the NAICS field is actually of uint64 type and not uint8. could be ?

**Comment by vladisld** [comment]
at https://github.com/akapur/pyiqfeed/blob/master/pyiqfeed/conn.py#L677

the NAICS field is defined as 'u8' numpy dtype - meaning uint64. 

`    fundamental_type = [
    ...
        ("NAICS", "u8"),
    ]
`

**Comment by akapur** [comment]
Happy to accept a pull request with a fix.

**Comment by vladisld** [comment]
https://github.com/akapur/pyiqfeed/pull/74

could you please review/approve?
